#!/bin/bash

if [ -e "$1" ]
then
  dist/build/LatteCompiler/LatteCompiler "$1" "${1%.*}.ast"
  if [ $? -ne 0 ]
  then
    echo "FAIL"
  else
    echo "PASS"
  fi
  #cat "${1%.*}.ast"
  #llvm-as -o "${1%.*}_tmp.bc" "${1%.*}.ll"
  #llvm-link -o "${1%.*}.bc" "${1%.*}_tmp.bc" lib/runtime.bc
  #rm "${1%.*}_tmp.bc"
else
  echo "Couldn't find file '$1'."
fi