#!/bin/bash

# all good basic
for f in $(find good/ -name '*.lat')
do
	echo $f
  #echo ${f%.*}.bc
	./latc_llvm $f
  DIFF=$(lli "${f%.*}.bc" | diff "${f%.*}.output" -)
  if [ "$DIFF" != "" ]
  then
    echo "RUN FAIL"
    echo $DIFF
  else
    echo "RUN PASS"
  fi
done

# all mrjp-good basic
for f in $(find mrjp-tests/good/basic -name '*.lat')
do
  echo $f
  #echo ${f%.*}.bc
  ./latc_llvm $f
  DIFF=$(lli "${f%.*}.bc" | diff "${f%.*}.output" -)
  if [ "$DIFF" != "" ]
  then
    echo "RUN FAIL"
    echo $DIFF
  else
    echo "RUN PASS"
  fi
done

# all good basic
#for f in $(find extensions/ -name '*.lat')
#do
#	echo $f
#	./latc_llvm $f
#done

# all good basic
#for f in $(find mrjp-tests/good -name '*.lat')
#do
#	echo $f
#	./latc_llvm $f
#done

# all good basic
#for f in $(find mrjp-tests/gr5 -name '*.lat')
#do
#	echo $f
#	./latc_llvm $f
#done

# all bad basic
#for f in $(find bad/ -name '*.lat')
#do
#	echo $f
#	./latc_llvm $f
#done

# all good structs
#for f in $(find extensions/objects1 extensions/objects2 extensions/struct mrjp-tests/good/virtual mrjp-tests/gr5 -name '*.lat')
#do
#	echo $f
#	./latc_llvm $f
#done